// ----------------------------------------
// src/includes/private-vars.js
// ----------------------------------------

var addToStoryCache = null, /* tmp cache, see addToStroy(), via InDesign external library file*/
  currAlign = null,
  currCanvasMode = null,
  currColorMode = null,
  currDialogFolder = null,
  currDoc = null,
  currEllipseMode = null,
  currFillColor = null,
  currFillTint = null,
  currFont = null,
  currFontSize = null,
  currGradientMode = null,
  currImageMode = null,
  currKerning = null,
  currLayer = null,
  currLeading = null,
  currMatrix = null,
  currMode = null,
  currPage = null,
  currPathPointer = null,
  currPolygon = null,
  currRectMode = null,
  currShapeMode = null,
  currStrokeColor = null,
  currStrokeTint = null,
  currStrokeWeight = null,
  currTracking = null,
  currUnits = null,
  currVertexPoints = null,
  currYAlign = null,
  matrixStack = null,
  noneSwatchColor = null,
  startTime = null;
